name: 'Setup Node & pnpm'
description: 'GitHub action that sets the node environment for a workflow and downloads pnpm dependencies.'
inputs:
  node_version:
    description: 'Node version'
    required: false
    default: '24'
  pnpm_version:
    description: 'pnpm version'
    required: false
    default: 'latest'

runs:
  using: 'composite'
  steps:
    - name: Setup pnpm
      uses: pnpm/action-setup@v4
      with:
        version: ${{ inputs.pnpm_version }}
        run_install: false

    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node_version }}
        registry-url: 'https://registry.npmjs.org'
        cache: pnpm
        cache-dependency-path: pnpm-lock.yaml

    - name: pnpm Install
      run: pnpm install --frozen-lockfile --ignore-scripts
      shell: bash
